/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RaceTrackIdRouteImport } from './routes/race.$trackId'
import { Route as GameCompleteRouteImport } from './routes/game.complete'
import { Route as GameLevelRouteImport } from './routes/game.$level'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceTrackIdRoute = RaceTrackIdRouteImport.update({
  id: '/race/$trackId',
  path: '/race/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCompleteRoute = GameCompleteRouteImport.update({
  id: '/game/complete',
  path: '/game/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLevelRoute = GameLevelRouteImport.update({
  id: '/game/$level',
  path: '/game/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/drivers': typeof DriversRoute
  '/garage': typeof GarageRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
  '/race/$trackId': typeof RaceTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/drivers': typeof DriversRoute
  '/garage': typeof GarageRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
  '/race/$trackId': typeof RaceTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/drivers': typeof DriversRoute
  '/garage': typeof GarageRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
  '/race/$trackId': typeof RaceTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/drivers'
    | '/garage'
    | '/profile'
    | '/quiz'
    | '/auth/callback'
    | '/game/$level'
    | '/game/complete'
    | '/race/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/drivers'
    | '/garage'
    | '/profile'
    | '/quiz'
    | '/auth/callback'
    | '/game/$level'
    | '/game/complete'
    | '/race/$trackId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/drivers'
    | '/garage'
    | '/profile'
    | '/quiz'
    | '/auth/callback'
    | '/game/$level'
    | '/game/complete'
    | '/race/$trackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DriversRoute: typeof DriversRoute
  GarageRoute: typeof GarageRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  GameLevelRoute: typeof GameLevelRoute
  GameCompleteRoute: typeof GameCompleteRoute
  RaceTrackIdRoute: typeof RaceTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race/$trackId': {
      id: '/race/$trackId'
      path: '/race/$trackId'
      fullPath: '/race/$trackId'
      preLoaderRoute: typeof RaceTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/complete': {
      id: '/game/complete'
      path: '/game/complete'
      fullPath: '/game/complete'
      preLoaderRoute: typeof GameCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$level': {
      id: '/game/$level'
      path: '/game/$level'
      fullPath: '/game/$level'
      preLoaderRoute: typeof GameLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DriversRoute: DriversRoute,
  GarageRoute: GarageRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  GameLevelRoute: GameLevelRoute,
  GameCompleteRoute: GameCompleteRoute,
  RaceTrackIdRoute: RaceTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
