/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameCompleteRouteImport } from './routes/game.complete'
import { Route as GameLevelRouteImport } from './routes/game.$level'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCompleteRoute = GameCompleteRouteImport.update({
  id: '/game/complete',
  path: '/game/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLevelRoute = GameLevelRouteImport.update({
  id: '/game/$level',
  path: '/game/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/game/$level': typeof GameLevelRoute
  '/game/complete': typeof GameCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/game/$level' | '/game/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/game/$level' | '/game/complete'
  id: '__root__' | '/' | '/quiz' | '/game/$level' | '/game/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  GameLevelRoute: typeof GameLevelRoute
  GameCompleteRoute: typeof GameCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/complete': {
      id: '/game/complete'
      path: '/game/complete'
      fullPath: '/game/complete'
      preLoaderRoute: typeof GameCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$level': {
      id: '/game/$level'
      path: '/game/$level'
      fullPath: '/game/$level'
      preLoaderRoute: typeof GameLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  GameLevelRoute: GameLevelRoute,
  GameCompleteRoute: GameCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
